name = "GitForge"
uuid = "8f6bce27-0656-5410-875b-07a5572985df"
authors = ["Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"

[compat]
JSON2 = ">= 0.3.0"
julia = ">= 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
